---
title: "HOMEWORK 1 - Creating Value Through Data Mining (S402010)"
author: "Liam Phan"
date: "`r Sys.Date()`"
output: html_document
---

# HOMEWORK 1 

## Settings Up

```{r 1, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
rm(list = ls()) # clean environment
```

# Loading Packages

```{r 2}

# Loading Packages 

library(data.table)
library(lubridate)
library(tidyverse)
library(esquisse)
library(plyr)
library(ggplot2)
library(cowplot)
library(naniar) #for NA exploration
library(sp) #spatial data
library(ggmap) #for map
library(osmdata) #openstreetmap
library(reshape2)
library(plotly)

```

## Loading Datas and Cleaning

```{r 3}

Laptop_Sales_Data <- fread("DATA/LaptopSales_red.csv")

is.data.table(Laptop_Sales_Data)

summary(Laptop_Sales_Data)

str(Laptop_Sales_Data)

gg_miss_var(Laptop_Sales_Data, show_pct = TRUE)

```

## EX 3.4 

### a.Price Question

```{r 4}

#### Set Up a Data Subset and NA OMIT

Retail_Price_and_Dates <- Laptop_Sales_Data[,.(Retail.Price,Date)][,Date:=mdy_hm(Date)]

Retail_Price_and_Dates <- na.omit(Retail_Price_and_Dates)

```

#### i.

```{r 5, fig.asp = 0.8, fig.width = 7}

#### Histogram of the Retail Price of Computer In 2018

ggplot(Retail_Price_and_Dates) +
 aes(x = Retail.Price) +
 geom_histogram(bins = 30L, fill = "#1c6155") +
 labs(x = "Price", y = "Frequency", title = "Histogram of the Retail Price of Computer", subtitle = "In 2018") +
 theme_classic()
 

#### Boxplot of the Retail Price of Computer In 2018

ggplotly(
ggplot(Retail_Price_and_Dates) +
 aes(x = "", y = Retail.Price) +
 geom_boxplot(fill = "#1c6155") +
 labs(y = "Price", 
 title = "Boxplot of the Retail Price of Computer", subtitle = "In 2018") +
 theme_classic()
)

# Actual price

Max_Date_Retail <- max(Retail_Price_and_Dates$Date)

Actual_Price <- Retail_Price_and_Dates[Date %in% Max_Date_Retail, ]

print(paste("Last Recorded Prices are", Actual_Price[1,1], "USD", "and", Actual_Price[2,1],"USD","on the same Day with a mean of",mean(Actual_Price$Retail.Price),"USD"))

 ```

#### ii.

```{r 6, fig.asp = 0.8, fig.width = 7}

days = list("Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche")

# Aggregating by Month
Retail_Price_and_Dates_Month <- Retail_Price_and_Dates[, mean(Retail.Price), by = floor_date(Date,unit="month")]

colnames(Retail_Price_and_Dates_Month)[1] <- "Date"
colnames(Retail_Price_and_Dates_Month)[2] <- "Mean_Retail_Price"

# Aggregating by Week
Retail_Price_and_Dates_Week <- Retail_Price_and_Dates[, mean(Retail.Price), by = floor_date(Date,unit = "week")]

colnames(Retail_Price_and_Dates_Week)[1] <- "Date"
colnames(Retail_Price_and_Dates_Week)[2] <- "Mean_Retail_Price"

# Aggregating by Day
Retail_Price_and_Dates_Day <- Retail_Price_and_Dates[, mean(Retail.Price), by = floor_date(Date,unit = "day")]

colnames(Retail_Price_and_Dates_Day)[1] <- "Date"
colnames(Retail_Price_and_Dates_Day)[2] <- "Mean_Retail_Price"

# Aggregating by Weekday

Retail_Price_and_Dates_WeekDay <- Retail_Price_and_Dates[,Weekday:=weekdays(Date)]
Retail_Price_and_Dates_WeekDay <- Retail_Price_and_Dates_WeekDay[,mean(Retail.Price),by=Weekday]

colnames(Retail_Price_and_Dates_WeekDay)[2] <- "Mean_Retail_Price"


# Retail Price By Month
RetailPricePlot1 <- ggplotly(
  ggplot(Retail_Price_and_Dates_Month) +
 aes(x = Date, y = Mean_Retail_Price) +
 geom_line(size = 1.1, 
 colour = "#1c6155") + geom_point() +
 labs(x = "Months", y = "Average Retail Pric", title = "Average Retail Price of Computer in 2018", 
 subtitle = "Aggregated by Month") +
 theme_classic()
 )

RetailPricePlot1

# Retail Price By Week
RetailPricePlot2 <- ggplotly(
  ggplot(Retail_Price_and_Dates_Week) +
 aes(x = Date, y = Mean_Retail_Price) +
 geom_line(size = 0.4, 
 colour = "#1c6155") + geom_point() +
 labs(x = "Weeks", y = "Average Retail Pric", title = "Average Retail Price of Computer in 2018", 
 subtitle = "Aggregated by Week") +
 theme_classic()
 )

RetailPricePlot2

# Retail Price By Day
RetailPricePlot3 <- ggplotly(
  ggplot(Retail_Price_and_Dates_Day) +
 aes(x = Date, y = Mean_Retail_Price) +
 geom_line(size = 0.2, 
 colour = "#1c6155") + geom_point() +
 labs(x = "Days", y = "Average Retail Price", title = "Average Retail Price of Computer in 2018", 
 subtitle = "Aggregated by Day") + 
 theme_classic()
 )

RetailPricePlot3

# Retail Price By Week Day

RetailPricePlot4 <- ggplotly(
  ggplot(Retail_Price_and_Dates_WeekDay) +
 aes(x = Weekday, y = Mean_Retail_Price) +
 geom_col(fill = "#1c6155") +
 labs(x = "Weekdays", y = "Average Retail Price", title = "Average Retail Price during Weekdays", subtitle = "In 2018") + 
 theme_classic() + coord_cartesian(ylim = c(500, 510))
)

RetailPricePlot4



```

#### iii.

```{r 7}

#### Set Up a Data Subset and NA OMIT

Retail_Price_Outlets_Date <- Laptop_Sales_Data[,.(Retail.Price,Store.Postcode,Date)][,Date:=mdy_hm(Date)]

Retail_Price_Outlets_Date  <- na.omit(Retail_Price_Outlets_Date)

Retail_Price_Configuration <- Laptop_Sales_Data[,.(Retail.Price,Configuration,Screen.Size..Inches.,Battery.Life..Hours.,RAM..GB.,Processor.Speeds..GHz.,Integrated.Wireless.,HD.Size..GB.,Bundled.Applications.)]

Retail_Price_Configuration <- na.omit(Retail_Price_Configuration)

```

```{r 8, fig.asp = 0.8, fig.width = 7}

#### Price Decomposed by Retail Outlets

#### Boxplot Across Retail Outlets

ggplotly(
ggplot(Retail_Price_Outlets_Date) +
 aes(x = Store.Postcode, y = Retail.Price) +
 geom_boxplot(fill = "#1c6155") +
 labs(x = "Stores Postcode", y = "Price", title = "Boxplot Of The Retail Price Across Stores", subtitle = "In 2018") +
 theme_classic() + scale_x_discrete(guide = guide_axis(n.dodge = 1)) + theme(axis.text.x=element_text(size=rel(1), angle=90))
)

#### Retail Price Across Stores During 2018 - Data

Retail_Price_Outlets_Date_Month <- Retail_Price_Outlets_Date[,Floor.Date:=floor_date(Date,unit="month")][,c(Mean_Price=mean(Retail.Price)), by=list(Store.Postcode,Floor.Date)]

colnames(Retail_Price_Outlets_Date_Month)[3] <- "Mean_Retail_Price"

#### Plot of the Monthly Retail Price per Stores

ggplot(Retail_Price_Outlets_Date_Month) +
 aes(x = Floor.Date, y = Mean_Retail_Price, colour = Store.Postcode) +
 geom_line(size = 0.5) +
 scale_color_hue(direction = 1) +
 labs(x = "Month", y = "Price", title = "Retail Price Across Months and Grouped by Stores", 
 subtitle = "In 2018") +
 theme_classic()


#### Plot Of The Retail Price per Configuration

ggplot(Retail_Price_Configuration) +
 aes(x = Configuration, y = Retail.Price) +
 geom_point(shape = "circle", size = 0.6) +
 scale_color_gradient() +
 labs(y = "Retail Price", title = "Retail Price and Configuration ", 
 subtitle = "In 2018") + geom_smooth()
 theme_classic()

``` 

### b.Location Questions

#### i.

```{r 9}




```

#### ii.

```{r 10, fig.asp = 0.8, fig.width = 7}

Laptop_Sales_Data_2 <- Laptop_Sales_Data

Sales_Stores <- Laptop_Sales_Data_2[, .N, by=Store.Postcode]

#### Plot Most Sales from Stores

ggplot(Sales_Stores) +
 aes(x = reorder(Store.Postcode,-N), y = N) +
 geom_col(fill = "#1c6155") +
 labs(x = "Stores", 
 y = "Number Of Transactions", title = "Number of Transactions per Store", subtitle = "In 2018") +
 theme_classic()  + geom_text(aes(label = N), vjust = 1.5, hjust=1.1, colour = "white", angle=90,size=3) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))




```

#### iii.

```{r 11}


```

### c.Revenue Questions

#### i.

```{r 12, fig.asp = 0.8, fig.width = 7}

Sales_Stores_Revenues <- Laptop_Sales_Data[,.(Volumes=.N, Revenues=sum(Retail.Price, na.rm = TRUE), Configuration), by= Store.Postcode]

ggplotly(
ggplot(Sales_Stores_Revenues) +
 aes(x = Volumes, y = Revenues, colour = Store.Postcode) +
 geom_point(shape = "circle", 
 size = 2L) +
 scale_color_hue(direction = 1) +
 labs(x = "Volumes", y = "Revenues", title = "Scatterplot Of Sales Volumes VS Sales Revenues ", 
 subtitle = "In 2018", color = "Stores") +
 theme_classic()
)

```


#### ii.

```{r 13,fig.asp = 0.8, fig.width = 7}

Sales_Stores_Revenues_Configuration_Ratio <- Sales_Stores_Revenues[, ratio_volume_revenue:=Revenues/Volumes]



```

### d.Configuration Questions 

#### i.

```{r 14, fig.asp = 0.8, fig.width = 7}

Detail_Price <- Laptop_Sales_Data[,.(Retail.Price,Screen.Size..Inches.,Battery.Life..Hours.,RAM..GB.,Processor.Speeds..GHz.,HD.Size..GB.)]

Detail_Price <- na.omit(Detail_Price)

```


#### ii.

```{r 15,fig.asp = 0.8, fig.width = 7}

Stores_Details <- Laptop_Sales_Data[,.(Store.Postcode,Integrated.Wireless.,Bundled.Applications.,Configuration)]

Stores_Details <- na.omit(Stores_Details)

ggplotly(
ggplot(Stores_Details) +
 aes(x = Store.Postcode, fill = Bundled.Applications.) +
 geom_bar() +
 scale_fill_brewer(palette = "Greens", 
 direction = 1) +
 labs(x = "Stores", y = "Count", title = "Stores Bundled Applications Count", 
 subtitle = "In 2018", fill = "Bundled Application") +
 theme_classic() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
)

ggplotly(
ggplot(Stores_Details) +
 aes(x = Store.Postcode, fill = Integrated.Wireless.) +
 geom_bar() +
 scale_fill_brewer(palette = "Greens", 
 direction = 1) +
 labs(x = "Stores", y = "Count", title = "Stores Integrated Wireless Count", 
 subtitle = "In 2018", fill = "Integrated Wireless") +
 theme_classic() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
)

```

